### ISSUE TITLE
Dependency issues

### ISSUE THREAD

**Issue by Andrew-Chen-Wang** [zankhq/astro-starter#21]
Hey, it seems like the dependencies can't be installed via `npm install` 

I deleted the pnpm lock file and others, but it's not properly installing. I went about trying to resolve the issues, but it's basically dependency hell:

For example:

```
npm ERR! Could not resolve dependency:
npm ERR! peer astro@"^2.0.0 || ^3.0.0" from astro-sveltia-cms@0.0.10
npm ERR! node_modules/astro-sveltia-cms
npm ERR!   astro-sveltia-cms@"^0.0.10" from the root project
```

I had upgraded astro to v4's latest version (currently out of date here), but it seems like the cms package is no longer up to date

**Comment by zanhk** [comment]
Hi @Andrew-Chen-Wang thanks for the segnalation, tomorrow I will take a look

**Comment by zanhk** [comment]
@Andrew-Chen-Wang should be fixed now

**Comment by Andrew-Chen-Wang** [comment]
Hi this is not fixed. Can you try doing these steps:

1. Create a new repository using this repo as a template
2. Then try running `npm install`

You still get 

```
npm install
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! While resolving: create-astro-starter@0.13.4
npm ERR! Found: astro@4.3.5
npm ERR! node_modules/astro
npm ERR!   astro@"^4.0.3" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer astro@"^3.5.5" from astro-i18n-aut@0.5.0
npm ERR! node_modules/astro-i18n-aut
npm ERR!   astro-i18n-aut@"^0.5.0" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
```

Please let me know when there are no dependency issues.

**Comment by Andrew-Chen-Wang** [comment]
@zanhk upgraded the dependency that fixes this issue and pnpm now locks properly.

**Comment by zanhk** [comment]
Thanks
